### PR TITLE
Increase page_size to 999 as request by Hazel Fletcher

### PR DESCRIPTION
**Pull request by chrisallmark**
Hi Andy,

Hazel Fletcher asked me to tweak a line of code on the ggideas app as she's been unable to contact you. I've forked the code and made the change - can you merge and deploy?

Regards,
Chris Allmark
chrisa@giffgaff.co.uk

### CODE REVIEW

**Comment by andypiper** [comment]
This is great Chris, thanks, I will take a look shortly.

**Comment by chrisallmark** [comment]
Hi Andy,

Any luck with this?

Chris

**Comment by andypiper** [comment]
fixed in Commit #b90ebab

**Comment by chrisallmark** [comment]
Super. Has this change been deployed to http://ggideas.cfapps.io/
 and I’ll let Hazel know.

Thanks,
Chris

Sent with Unibox

**Pull request closed without merging**
